version: "3.3"

services:
  ansible:
    image: registry.localdomain/ansible
    working_dir: /home/ansible/ansible
    user: ansible
    volumes:
      - ansible-galaxy:/etc/ansible/roles
      - ./ansible:/home/ansible/ansible
      - ./docker/python/nopass_key:/key/nopass_key
    env_file: .env
volumes:
  ansible-galaxy:
