master-node:
  hosts:
    master:
      ansible_host: 172.16.20.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: /key/.vagrant/machines/master-node/virtualbox/private_key
  vars:
    kubernetes_role: "master"
    kubernetes_apiserver_advertise_address: 172.16.20.3
worker-node:
  hosts:
    worker-1:
      ansible_host: 172.16.20.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: /key/.vagrant/machines/workernode-1/virtualbox/private_key
    worker-2:
      ansible_host: 172.16.20.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: /key/.vagrant/machines/workernode-2/virtualbox/private_key
    worker-3:
      ansible_host: 172.16.20.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: /key/.vagrant/machines/workernode-3/virtualbox/private_key
  vars:
    kubernetes_role: "node"
