---
- hosts: docker
  become: true
  tasks:

    - name: package install
      apt:
        pkg:
          - vim
          - git
          - nfs-common

    - name: docker-compose-delete
      file:
        path: /usr/local/bin/docker-compose
        state: absent

    - name: install docker-compose
      pip:
        name: docker-compose

  roles:
    - geerlingguy.docker
