web:
  hosts:
    pi1:
      ansible_host: 192.168.0.4
      ansible_user: root
      ansible_ssh_private_key_file: /key/nopass_key
    pi2:
      ansible_host: 192.168.0.5
      ansible_user: root
      ansible_ssh_private_key_file: /key/nopass_key
    pi3:
      ansible_host: 192.168.0.6
      ansible_user: root
      ansible_ssh_private_key_file: /key/nopass_key
    pi4:
      ansible_host: 192.168.0.7
      ansible_user: root
      ansible_ssh_private_key_file: /key/nopass_key