---
- hosts: web
  become: true
  tasks:
    - name: anyenv* package install
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - libffi-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libzip-dev
        - libjpeg-dev
        - libpng-dev
        - libxml2-dev
        - libssl-dev
        - libtidy-dev
        - libxslt-dev
        - libmcrypt-dev
        - libreadline-dev
        - re2c
        - bison
        - curl
        - autoconf
        - automake
        - libssl-dev
        - libreadline-dev